language: generic
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  jobs:
    # Disabled all versions prior to 26.3 because the undo-tree is unsigned on ELPA
    # preventing its download. This bug has only been fixed since 26.3, and AFAIK
    # there is no way to use a workaround with cask
    # - EMACS_VERSION=25.2
    # - EMACS_VERSION=25.3
    # - EMACS_VERSION=26.1
    # - EMACS_VERSION=26.2
    - EMACS_VERSION=26.3
    - EMACS_VERSION=27.1
branches:
  only:
    - master
    - dev
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - git clone --depth=1 https://github.com/cask/cask.git "$HOME/.cask"
  - ln -s "$HOME/.cask/bin/cask" "$HOME/bin/cask"
  - $EMACS --version
install:
  # verbose flag prevents https://github.com/cask/cask/issues/367
  - cask install --verbose
script:
  - make lint
  - make compile
  - make test
notifications:
  email:
    on_success: never
    on_failure: always
